### ISSUE TITLE
missing argument: 'levels'

### ISSUE THREAD

**Issue by JieunLee017** [quarkslab/diffing_obfuscation_dataset#4]
~/diffing_obfuscation_dataset$ obfu-dataset-cli download-plain -r dataset/ -t 5
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/obfu-dataset-cli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/obfuscation-dataset/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/obfuscation-dataset/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/obfuscation-dataset/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/obfuscation-dataset/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/obfuscation-dataset/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/pipx/venvs/obfuscation-dataset/lib/python3.12/site-packages/obfu_dataset/__main__.py", line 306, in download_plain
    download_packages(root, threads, BinaryType.PLAIN, projects, [], [])
TypeError: download_packages() missing 1 required positional argument: 'levels'

=> how can I solve this error?

**Comment by RobinDavid** [comment]
Nice. Catch we forgot to forward additional parameters to that function. As we are working on the code it was a bit broken.

I just fixed it: https://github.com/quarkslab/diffing_obfuscation_dataset/commit/bd402fa72897cf0dfc9e79cc66f7310d2812b461

Let us know if that works.

Note: We will soon push updated .zip files on the AWS bucket. So it might be worth it to wait just a little while.

**Comment by roxanecohen** [comment]
Hello, 
Updated files were uploaded on the server and you can now download them. If you encounter any other error, please let us know.
